services:
  bot:
    container_name: doom-bot
    build: .
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_USER=${PSQL_USER}
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_DATABASE=${PSQL_DATABASE}
      - PSQL_PORT=${PSQL_PORT}
    networks:
      - doom-network

networks:
  doom-network:
    external: true
